### PR TITLE
FOGL-8679: Fixed plugin version tooltip issue on south and north page for flow editor

### PR DESCRIPTION
**Pull request by hemantgarg923**

### CODE REVIEW

**Review by praveen-garg — COMMENTED** [review]
Explanation of true to false switching?

**Review by praveen-garg — COMMENTED** [review]
Filter
Rule/Notify all okay?

**Comment by hemantgarg923** [comment]
> Filter Rule/Notify all okay?

Currently version tooltip is available only on south and north services/tasks

**Comment by hemantgarg923** [comment]
> Explanation of true to false switching?

Here true/false is used for caching. Previously the call was cached, which should not be the case so switched to cached=false.

**Review by mshariq-nerd — APPROVED** [review]

**Pull request merged**
